"""Autoregressive one-step-ahead generative model (Rung G3 of the
market-generator comparison suite): reuses TCNEncoder (causal dilated
convs, already validated in models/tcn_vae.py) but trained to predict the
NEXT step's return distribution rather than to reconstruct a fixed
window.

Exists because models.tcn_vae.TCNVAE structurally cannot do free-running
generation: its decode(z, h_seq) requires h_seq from encoding a REAL
input window at every position it reconstructs (added as the fix for a
real flat-reconstruction bug, see
diagnostics/2026-08-11-tcn-vae-flat-reconstruction/), and there is no
"extend one step past the window" operation defined anywhere in that
class -- it was only ever trained to reproduce its input, not extrapolate
past it. A genuinely autoregressive model (DeepAR-style: predict a
conditional distribution at every step, then ancestral-sample forward) is
the correct tool for generating a new synthetic path.

n_features=2 by default ([log_return, realized_vol], deliberately NOT
volume_zscore): realized_vol can be recomputed from the model's own
generated returns at each ancestral-sampling step
(models/forecaster_generate.py), but volume can't be generated by this
design -- feeding a frozen fake constant during free-running generation
would silently bake a fake constant-volume assumption into every
synthetic path. Real volume dynamics are out of scope for this generator,
documented rather than faked.
"""

from __future__ import annotations

import torch
import torch.nn as nn

from models.tcn_vae import TCNEncoder


class TCNForecaster(nn.Module):
    def __init__(
        self,
        n_features: int = 2,
        hidden_dim: int = 16,
        kernel_size: int = 3,
        dilations: tuple[int, ...] = (1, 2, 4, 8),
        dropout: float = 0.1,
    ):
        super().__init__()
        self.encoder = TCNEncoder(n_features, hidden_dim, kernel_size, dilations=dilations, dropout=dropout)
        self.fc_mean = nn.Linear(hidden_dim, 1)
        self.fc_logvar = nn.Linear(hidden_dim, 1)

    def forward(self, x: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        """x: (B, T, n_features). Returns (mean, logvar), each (B, T):
        mean[:, t]/logvar[:, t] is this position's causal one-step-ahead
        prediction of log_return at t+1, using only x[:, :t+1] (the
        encoder is causal by construction -- see
        test_tcn_forecaster.py::test_no_lookahead).

        logvar clamped to [-20, 0], NOT TCNVAE's [-6, 6] -- that range was
        blindly copied from TCNVAE's KL-divergence numerical-stability
        context and is wrong here. Confirmed on real SPY data
        (diagnostics/2026-08-12-tcn-forecaster-generative/): minute-bar
        log_return has std~0.00035 (log-variance~-15.9), with even the
        single largest real move in the dataset corresponding to
        log-variance~-10.4. A [-6,6] clamp floors every prediction's std
        at exp(-3)~0.05 -- ~140x too large -- and the model, trying to
        express a correctly tiny variance, gets silently pinned at that
        floor on *every* position regardless of input (measured: min==max
        predicted std to 5 decimal places on a real window). [-20, 0]
        gives headroom down to std~4.5e-5 and up to std=1, comfortably
        covering the real range with margin on both sides.
        """
        h_seq = self.encoder(x)  # (B, T, hidden_dim)
        mean = self.fc_mean(h_seq).squeeze(-1)
        logvar = self.fc_logvar(h_seq).clamp(-20, 0).squeeze(-1)
        return mean, logvar
